global using Domain.Email.Entities.Enums;
global using Domain.Common.ValueObjects;
global using Domain.Email.ValueObjects;
global using Domain.User.ValueObjects;
global using Domain.User.Entities;
global using Domain.Email.Entities;
global using NUnit.Framework;
global using Domain.Common.Exceptions;
global using Domain.Email.Exceptions;